### PR TITLE
Create test2

### PR DESCRIPTION
**Pull request by coqbot-dev-tester**

### CODE REVIEW

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because there is still a `needs: rebase` label.

**Comment by coqbot-dev** [comment]
test

**Comment by coqbot-dev** [comment]
ping @coqbot-dev-tester

**Comment by coqbot-dev** [comment]
ping @coqbot-dev

**Comment by coqbot-dev-tester** [comment]
ping @coqbot-dev

**Comment by coqbot-dev** [comment]
@coqbot-dev merge now

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because there is no `kind:` label.

**Comment by coqbot-dev** [comment]
@coqbot-dev merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because no milestone is set.

**Comment by coqbot-dev** [comment]
please merge @coqbot-dev Merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because it hasn't been approved yet.

**Comment by coqbot-dev** [comment]
@coqbot-dev Merge now!

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because it hasn't been approved yet.

**Comment by coqbot-dev** [comment]
@coqbot-dev Merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged by email.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: Merge requests sent over e-mail are not accepted because this put less guarantee on the authenticity of the author of the request.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because it hasn't been approved yet.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: run CI now

**Comment by coqbot-dev** [comment]
@coqbot: run CI now

**Comment by coqbot-dev** [comment]
@coqbot: minimize
```
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev: minimize
```
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now!!!

**Comment by coqbot-dev** [comment]
@coqbot-dev: good bot

**Pull request merged**
