### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by coqbot-dev-tester**
again

### CODE REVIEW

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: Merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: Merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: Merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: Merge now

**Comment by coqbot-dev** [comment]
@coqbot: minimize
```bash 
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev minimize
```bash
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev minimize
```bash
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev minimize
```
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev minimize
```
opam install -y coq-ext-lib
eval $(opam env)
mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Pull request merged**
