### PR TITLE
Create test3

### PR DESCRIPTION
**Pull request by coqbot-dev-tester**

### CODE REVIEW

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because there is no `kind:` label.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because no milestone is set.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: This PR cannot be merged because some changes are requested.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: You can't merge the PR because you're not among the assignees.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: You can't merge this PR because you're not a member of the `@coq/pushers` team.

**Comment by coqbot-dev-tester** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev-tester: You can't merge the PR because you are the author.

**Comment by coqbot-dev** [comment]
@coqbot-dev: merge now

**Comment by coqbot-dev** [comment]
@coqbot-dev: Please take care of the following overlays:
- test3

**Pull request merged**
